version: '3'

services:
  agents:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agents
    ports:
      - "10002:80"
    depends_on:
      - agentsdb

  agentsdb:
    image: mysql:latest
    container_name: agents-db
    environment:
      MYSQL_ROOT_PASSWORD: infected
      MYSQL_DATABASE: agentless
      MYSQL_USER: risdu
      MYSQL_PASSWORD: infected
    volumes:
      - ./db/data/:/var/lib/mysql
      - ./db/agentless.sql:/docker-entrypoint-initdb.d/agentless.sql